export const PAGE_TITLE_MAP = {
  "/access/[serviceId]/[environmentId]/events": "Events",
  "/access/[serviceId]/[environmentId]/access-control": "Access Control",
  "/access/[serviceId]/[environmentId]/dashboard": "Dashboard",
  "/access/service/[serviceId]": "Resources",
  "/access/[serviceId]/[environmentId]/[resourceId]/[resourceInstanceId]":
    "Resource",
  "/access/api-document": "API Documentation",
  "/marketplace/mysubsc": "My Subscriptions",
  "/settings": "Profile Settings",
  "/signin": "Sign In",
  "/signup": "Sign Up",
  "/reset-password": "Reset Password",
  "/billing": "Billing",
  "/subscriptions": "Subscriptions",
  "/service-plans": "Billing Plans",
  "/access/[serviceId]/[environmentId]/audit-logs": "Audit Logs",
  "/access/[serviceId]/[environmentId]/notifications": "Notifications",

  // dashboard: { title: "Dashboard" },
  // instances: { title: "Instances" },
  // customNetworks: { title: "Custom Networks" },
  // cloudAccounts: { title: "Cloud Accounts" },
  // accessControl: { title: "Access Control" },
  // auditLogs: { title: "Audit Logs" },
  // notifications: { title: "Notifications" },
  // settings: { title: "Settings" },
  // billing: { title: "Billing" },
  // subscriptions: { title: "Subscriptions" },
  // apiDocumentation: { title: "API Documentation" },
};
